name: Ruby

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.5'
    services:
      nats:
        image: nats:latest
        ports: ["4222:4222", "6222:6222", "8222:8222"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run the default task
        run: bundle exec rake
        env:
          NATS_URI: nats://nats:4222
